---
title: "GPA Project"
author: "Nick Tandle"
date: "2/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Packages:
```{r}
install.packages("rvest")
install.packages("stringr")
install.packages("readxl")

library("rvest")
library("stringr")
library("readxl")
```


Getting Course GPA Dataset
```{r, eval=FALSE}
wade_datasetV2 <- read_excel("Wade_DatasetV2.xlsx",
                             sheet = "TestSpring2018")
```


Creation of URLs for extraction
```{r}
course_abbreviations= unique(wade_datasetV2$Subject)

final_course_urls= paste0("http://catalog.illinois.edu/courses-of-instruction/",tolower(course_abbreviations),"/")
```


Extracting credit hours from the URLs  of each course.

Not generalized yet:
```{r}
Course_credits =
  read_html(psyc) %>%
  html_nodes(".courseblocktitle") %>%
  html_text() %>%
  str_extract_all(, pattern = "credit:[:blank:][:digit:][:blank:]to[:blank:][:digit:]|credit:[:blank:][:digit:]")
```
Generalized:
```{r}
credit_function= function(x){
  tryCatch(
  read_html(x) %>%
  html_nodes(".courseblocktitle") %>%
  html_text() %>%
  str_extract_all(, pattern = "credit:[:blank:][:digit:][:blank:]to[:blank:][:digit:]|credit:[:blank:][:digit:]"),
  error = function(e) {NA})
  }
```




Extracting course abbreviation

Not generalized yet:
```{r}
Course_abbreviations=
read_html(psyc) %>%
  html_nodes(".courseblocktitle") %>%
  html_text() %>%
  str_extract_all(pattern= "PSYC[:blank:][:digit:]{3}") %>%
  str_replace_all(pattern = "[:blank:]", replacement = "")
```

Generalized:
```{r}
abb_function = function(x) {
  tryCatch(
    read_html(x) %>%
      html_nodes(".courseblocktitle") %>%
      html_text() %>%
      str_extract(pattern = "[:alpha:]{2,4}[:blank:][:digit:]{3}") %>%
      str_replace_all(pattern = "[:blank:]", replacement = ""),
    error = function(e) {NA}
  )
}
```


extracting all course abbreviations and credit hours
```{r}
all_abbreviations= mapply(FUN = abb_function, final_course_urls)
all_credits= mapply(FUN = credit_function, final_course_urls)
```


combining all 
```{r}
head_abb=head(all_abbreviations,2)


abb_cred_all=data.frame(all_abbreviations,all_credits)
```

```{r}
library(xlsx)
write.xlsx(mydata, "c:/mydata.xlsx")
```





