---
title: "GPAProjectProjectionScraps"
author: "Nick Tandle"
date: "2/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

**Testing merging abrev and credit hours
```{r}
test_credit = as.character(testing_credits)
test_abrev = as.character(Psych_course_abbreviations)
psyc_final = data.frame(as.vector(test_abrev), as.vector(test_credit))

```



Now creating a generalized program that will extract the course names and their corresponding credit hours from the list of all college department URLs.

Showing first few urls to be put into function.
```{r}
head(final_course_urls)

```

Small subset of URLS for testing as I create function:
```{r}
Some_Course_URLs=head(final_course_urls)

```


```{r}
test_url="http://catalog.illinois.edu/courses-of-instruction/ae/"

abb_function(test_url)


{
read_html(test_url) %>%
  html_nodes(".schedlink") %>%
  html_text() %>%
  str_extract_all(pattern= "[:alpha:]{3,4}[:blank:][:digit:]{3}") %>%
  str_replace_all(pattern = "[:blank:]", replacement = "")
}


test= mapply(FUN = abb_function, Some_Course_URLs)
test2= mapply(FUN = credit_function, Some_Course_URLs)
test2

engl_url="http://catalog.illinois.edu/courses-of-instruction/engl/"
abb_function(engl_url)
credit_function(engl_url)


  read_html(engl_url) %>%
  html_nodes(".courseblocktitle") %>%
  html_text() %>%
  str_extract_all(, pattern = "credit:[:blank:][:digit:]")
```


```{r}
  read_html(engl_url) %>%
  html_nodes(".courseblocktitle") %>%
  html_text() %>%
  str_extract_all(, pattern = "credit:[:blank:][:digit:][:blank:]to[:blank:][:digit:]|credit:[:blank:][:digit:]")
```



figuring out combining the credits and abbreviations:
```{r}
head_abb=head(all_abbreviations,2)
head_credit= head(all_credits,2)



do.call(rbind, Map(data.frame, A=as.character(head_abb), B=as.character(head_credit)))

summary(head_abb)
summary(as.character(head_credit))
```















